import {
  existsSync,
  mkdirSync,
  copyFileSync,
  readdirSync,
  appendFileSync,
  readFileSync,
  writeFileSync,
} from 'fs';
import { execSync } from 'child_process';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';
import { getRepoRoot } from '../config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Check if a CLI tool is installed
function isInstalled(command: string): boolean {
  try {
    execSync(`which ${command}`, { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

// Prompt helper with default value
async function promptWithDefault(
  rl: ReturnType<typeof createInterface>,
  question: string,
  defaultValue: string,
): Promise<string> {
  return new Promise((resolve) => {
    const displayDefault = defaultValue ? ` [${defaultValue}]` : '';
    rl.question(`${question}${displayDefault}: `, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

// Prompt for secret (no default shown)
async function promptSecret(
  rl: ReturnType<typeof createInterface>,
  question: string,
): Promise<string> {
  return new Promise((resolve) => {
    rl.question(`${question}: `, (answer) => {
      resolve(answer.trim());
    });
  });
}

export async function initProject(): Promise<void> {
  const projectRoot = getRepoRoot();

  console.log('');
  console.log('╔════════════════════════════════════════╗');
  console.log('║     Ralph - Setup Wizard               ║');
  console.log('╚════════════════════════════════════════╝');
  console.log('');
  console.log(`Initializing in: ${projectRoot}`);
  console.log('');

  // 1. Check installed providers
  const claudeInstalled = isInstalled('claude');
  const codexInstalled = isInstalled('codex');

  console.log('Detected providers:');
  console.log(`  Claude Code: ${claudeInstalled ? '✓ installed' : '✗ not found'}`);
  console.log(`  Codex CLI:   ${codexInstalled ? '✓ installed' : '✗ not found'}`);
  console.log('');

  if (!claudeInstalled && !codexInstalled) {
    console.error('Error: No LLM provider found. Install Claude Code or Codex CLI first.');
    console.error('  Claude Code: npm install -g @anthropic-ai/claude-code');
    console.error('  Codex CLI:   See https://github.com/openai/codex');
    process.exit(1);
  }

  // 2. Create .ralph/ directory
  const ralphDir = join(projectRoot, '.ralph');
  if (!existsSync(ralphDir)) {
    mkdirSync(ralphDir, { recursive: true });
  }

  // 3. Load existing config if present
  const envPath = join(ralphDir, 'env');
  const existingEnv = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : '';

  const getExisting = (key: string): string => {
    const match = existingEnv.match(new RegExp(`${key}=(.+)`));
    return match ? match[1] : '';
  };

  // 4. Interactive setup
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  // Linear credentials
  console.log('─── Linear Configuration ───');
  console.log('Get your API key from: https://linear.app/settings/api');
  console.log('');

  let linearApiKey: string;
  if (getExisting('LINEAR_API_KEY')) {
    console.log('LINEAR_API_KEY: (already configured)');
    linearApiKey = getExisting('LINEAR_API_KEY');
  } else {
    linearApiKey = await promptSecret(rl, 'LINEAR_API_KEY');
  }

  let linearTeamKey: string;
  if (getExisting('LINEAR_TEAM_KEY')) {
    console.log('LINEAR_TEAM_KEY: (already configured)');
    linearTeamKey = getExisting('LINEAR_TEAM_KEY');
  } else {
    linearTeamKey = await promptWithDefault(rl, 'LINEAR_TEAM_KEY (e.g., RSK)', '');
  }

  console.log('');

  // Provider selection
  console.log('─── Provider Configuration ───');
  const defaultProvider = claudeInstalled ? 'claude' : 'codex';
  const provider = await promptWithDefault(rl, 'Provider (claude/codex)', defaultProvider);

  let claudeModel = 'opus';
  let codexModel = 'gpt-5.2';
  let codexEffort = 'high';

  if (provider === 'claude') {
    claudeModel = await promptWithDefault(rl, 'Claude model (opus/sonnet/haiku)', 'opus');
  } else {
    codexModel = await promptWithDefault(rl, 'Codex model', 'gpt-5.2');
    codexEffort = await promptWithDefault(rl, 'Reasoning effort (low/medium/high/extra_high)', 'high');
  }

  console.log('');

  // Iteration limit
  console.log('─── Loop Configuration ───');
  const maxIterations = await promptWithDefault(rl, 'Max iterations (0 = unlimited)', '0');

  rl.close();

  // 5. Save configuration
  const envContent = `# Ralph Configuration
# Generated by ralph init

# Linear (required)
LINEAR_API_KEY=${linearApiKey}
LINEAR_TEAM_KEY=${linearTeamKey}

# Provider: "claude" or "codex"
RALPH_PROVIDER=${provider}

# Claude options
RALPH_CLAUDE_MODEL=${claudeModel}

# Codex options
CODEX_MODEL=${codexModel}
CODEX_REASONING_EFFORT=${codexEffort}

# Loop options (0 = unlimited)
RALPH_MAX_ITERATIONS=${maxIterations}
`;

  writeFileSync(envPath, envContent);
  console.log('');
  console.log('Saved configuration to .ralph/env');

  // 6. Configure MCP for Linear (Claude Code needs this)
  const mcpPath = join(ralphDir, 'mcp.json');
  const mcpConfig = {
    mcpServers: {
      linear: {
        type: 'http',
        url: 'https://mcp.linear.app/mcp',
        headers: {
          Authorization: `Bearer ${linearApiKey}`,
        },
      },
    },
  };
  writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + '\n');
  console.log('Configured Linear MCP in .ralph/mcp.json');

  // 7. Add .ralph/ to .gitignore
  const gitignorePath = join(projectRoot, '.gitignore');
  const gitignoreEntry = '.ralph/';

  if (existsSync(gitignorePath)) {
    const content = readFileSync(gitignorePath, 'utf-8');
    if (!content.includes(gitignoreEntry)) {
      appendFileSync(gitignorePath, `\n# Ralph runtime data\n${gitignoreEntry}\n`);
      console.log('Added .ralph/ to .gitignore');
    }
  } else {
    writeFileSync(gitignorePath, `# Ralph runtime data\n${gitignoreEntry}\n`);
    console.log('Created .gitignore with .ralph/');
  }

  // 8. Copy Claude Code commands
  // When installed via npm: __dirname is node_modules/@leixusam/ralph/dist/lib
  // commands are at: node_modules/@leixusam/ralph/.claude/commands
  const sourceCommandsDir = join(__dirname, '../../.claude/commands');
  const targetCommandsDir = join(projectRoot, '.claude', 'commands');

  if (existsSync(sourceCommandsDir)) {
    if (!existsSync(targetCommandsDir)) {
      mkdirSync(targetCommandsDir, { recursive: true });
    }

    const files = readdirSync(sourceCommandsDir).filter((f) => f.endsWith('.md'));
    for (const file of files) {
      copyFileSync(join(sourceCommandsDir, file), join(targetCommandsDir, file));
    }
    if (files.length > 0) {
      console.log(`Installed ${files.length} Claude Code command(s) to .claude/commands/`);
    }
  }

  // 9. Create thoughts/ directory
  const thoughtsDir = join(projectRoot, 'thoughts');
  if (!existsSync(thoughtsDir)) {
    mkdirSync(thoughtsDir, { recursive: true });
    console.log('Created thoughts/ directory');
  }

  console.log('');
  console.log('╔════════════════════════════════════════╗');
  console.log('║  ✓ Ralph initialized!                  ║');
  console.log('║                                        ║');
  console.log('║  Next steps:                           ║');
  console.log('║  1. Run `ralph` to start the loop      ║');
  console.log('║  2. Or open Claude Code in this dir    ║');
  console.log('╚════════════════════════════════════════╝');
}
